include: package:lint_hard/all.yaml

plugins:
  lint_hard:
    diagnostics:
      document_thrown_exceptions: true
      throws_index_up_to_date: true
      fields_first_constructors_next: true
      unthrown_exceptions_documented: true

linter:
  rules:
    always_use_package_imports : true
    prefer_relative_imports: false
    